services:
  - type: web
    name: hosmasy-web
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: hosmasy-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: hosmasy-redis
          property: connectionString

  - type: redis
    name: hosmasy-redis
    plan: free
    region: oregon

databases:
  - name: hosmasy-db
    plan: free
    region: oregon
